#!/usr/bin/env bash
# ============================================================
# sync-swarmclaw.sh — Single source of truth: /root/str-stack/.env
# Generates /root/.swarmclaw/.env and patches config.yaml tokens
# Run after ANY token regeneration or .env edit.
# ============================================================
set -euo pipefail

SOURCE="/root/str-stack/.env"
SWARM_ENV="/root/.swarmclaw/.env"
SWARM_YAML="/root/.swarmclaw/config.yaml"
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

if [ ! -f "$SOURCE" ]; then
  echo "ERROR: $SOURCE not found"
  exit 1
fi

get_val() {
  local val
  val=$(grep "^${1}=" "$SOURCE" 2>/dev/null | head -1 | sed "s/^${1}=//" | sed 's/^"//;s/"$//')
  echo "${val:-}"
}

echo "[$NOW] Syncing SwarmClaw from $SOURCE"

# ── 1. Generate SwarmClaw .env from main .env ──
GHL_API_VER=$(get_val GHL_API_VERSION)
[ -z "$GHL_API_VER" ] && GHL_API_VER=$(get_val GHL_VERSION)
[ -z "$GHL_API_VER" ] && GHL_API_VER="2021-07-28"

cat > "$SWARM_ENV" << ENVEOF
# =============================================================================
# SwarmClaw Environment — AUTO-GENERATED by sync-swarmclaw.sh
# Source of truth: /root/str-stack/.env
# Last synced: $NOW
# DO NOT EDIT THIS FILE — edit /root/str-stack/.env then run sync-swarmclaw.sh
# =============================================================================

# --- GHL API -----------------------------------------------------------------
GHL_API_VERSION=$GHL_API_VER
GHL_API_BASE=$(get_val GHL_API_BASE)

# --- GHL Tokens --------------------------------------------------------------
GHL_CALL_CENTER_TOKEN=$(get_val GHL_CALL_CENTER_TOKEN)
GHL_MASTER_TOKEN=$(get_val GHL_MASTER_TOKEN)

# --- GHL Location IDs --------------------------------------------------------
GHL_LOCATION_CALL_CENTER=$(get_val GHL_CALL_CENTER_LOCATION)
GHL_LOCATION_MASTER=$(get_val GHL_MASTER_LOCATION)

# --- GHL Pipeline: Owner Sales — Call Center ---------------------------------
GHL_PIPELINE_ID=$(get_val GHL_PIPELINE_ID)
GHL_STAGE_CALL_QUEUE=$(get_val GHL_STAGE_CALL_QUEUE)
GHL_STAGE_ATTEMPTED=$(get_val GHL_STAGE_ATTEMPTED)
GHL_STAGE_OVERFLOW_VAPI=$(get_val GHL_STAGE_OVERFLOW_VAPI)
GHL_STAGE_CONNECTED_DQ=$(get_val GHL_STAGE_CONNECTED_DQ)
GHL_STAGE_QUALIFIED_NB=$(get_val GHL_STAGE_QUALIFIED_NB)
GHL_STAGE_BOOKED=$(get_val GHL_STAGE_BOOKED)
GHL_STAGE_CONTRACT_SENT=$(get_val GHL_STAGE_CONTRACT_SENT)
GHL_STAGE_CLOSED_LOST=$(get_val GHL_STAGE_CLOSED_LOST)

# --- Instantly ----------------------------------------------------------------
INSTANTLY_API_KEY=$(get_val INSTANTLY_API_KEY)

# --- OpenAI -------------------------------------------------------------------
OPENAI_API_KEY=$(get_val OPENAI_API_KEY)

# --- Redis --------------------------------------------------------------------
REDIS_URL=redis://127.0.0.1:6379

# --- SwarmClaw ----------------------------------------------------------------
SWARMCLAW_PORT=$(get_val SWARMCLAW_PORT)
SWARMCLAW_DATA_DIR=$(get_val SWARMCLAW_DATA_DIR)
SWARMCLAW_ACCESS_KEY=$(get_val SWARMCLAW_ACCESS_KEY)

# --- Cost Guardrails ----------------------------------------------------------
DAILY_COST_LIMIT=$(get_val DAILY_COST_LIMIT)
TOKEN_CAP_PER_TASK=$(get_val TOKEN_CAP_PER_TASK)
ENVEOF

echo "  Written: $SWARM_ENV"

# ── 2. Patch tokens in config.yaml ──
if [ -f "$SWARM_YAML" ]; then
  MASTER_TOKEN=$(get_val GHL_MASTER_TOKEN)
  CC_TOKEN=$(get_val GHL_CALL_CENTER_TOKEN)

  cp "$SWARM_YAML" "${SWARM_YAML}.bak"

  python3 << PYEOF
import re

with open("$SWARM_YAML", "r") as f:
    yaml = f.read()

yaml = re.sub(
    r"(name: GHL Call Center.*?token:\s*)(\S+)",
    r"\g<1>$CC_TOKEN",
    yaml, count=1, flags=re.DOTALL
)

yaml = re.sub(
    r"(name: GHL Master.*?token:\s*)(\S+)",
    r"\g<1>$MASTER_TOKEN",
    yaml, count=1, flags=re.DOTALL
)

with open("$SWARM_YAML", "w") as f:
    f.write(yaml)

print("  Patched: $SWARM_YAML")
PYEOF
fi

# ── 3. Verify sync ──
echo ""
echo "  Verification:"

M_OAUTH=$(get_val GHL_MASTER_OAUTH)
C_OAUTH=$(get_val GHL_CALL_CENTER_OAUTH)
M_TOKEN=$(get_val GHL_MASTER_TOKEN)
C_TOKEN=$(get_val GHL_CALL_CENTER_TOKEN)

echo "  main .env GHL_MASTER_OAUTH:       ${M_OAUTH:0:12}..."
echo "  main .env GHL_MASTER_TOKEN:        ${M_TOKEN:0:12}..."
echo "  main .env GHL_CALL_CENTER_OAUTH:   ${C_OAUTH:0:12}..."
echo "  main .env GHL_CALL_CENTER_TOKEN:   ${C_TOKEN:0:12}..."

if [ "$M_TOKEN" = "$M_OAUTH" ] && [ "$C_TOKEN" = "$C_OAUTH" ]; then
  echo ""
  echo "  ALL TOKENS IN SYNC"
else
  echo ""
  echo "  WARNING: Alias mismatch detected!"
  if [ "$M_TOKEN" != "$M_OAUTH" ]; then
    echo "  -> GHL_MASTER_TOKEN != GHL_MASTER_OAUTH — update GHL_MASTER_TOKEN"
  fi
  if [ "$C_TOKEN" != "$C_OAUTH" ]; then
    echo "  -> GHL_CALL_CENTER_TOKEN != GHL_CALL_CENTER_OAUTH — update GHL_CALL_CENTER_TOKEN"
  fi
fi

echo ""
echo "[$NOW] Sync complete"
